getsentry/freight

- docs/quickstart.rst
- freight/api/task_index.py
- tests/api/test_task_index.py
- :current will target the latest finished task
- :previous will target the previous (one before latest) finished task
this will filter out any task matching :current's sha
> Internal refs for deploying known tasks

- Procfile
- bin/worker
- freight/api/task_index.py
- freight/config.py
- freight/tasks/check_queue.py
- tests/api/test_task_index.py
- tests/tasks/test_check_queue.py
- One queue per APP_ID + ENV
- Items become marked as in_progress upon entering execute_task queue
- Task creation no longer forces task execution
- Task execution no longer blocks on existing tasks
Refs GH-29
> Support queued deploys

- app.json
The main fix here is changing the dyno names from the old `"1X"` `"free"` (as this was causing deploy on heroku to fail).
While I was at it, I also added configuration for the logo and some missing configuration variables (the github token, most importantly).
~~I'm running a deployment right now, just to double-check that everything is fine.~~ deploy using this configuration was fine.
BTW, let me know if you want me to squash commits into one, as it's a small enough change.
Cheers
> Fix heroku deploy button

- app.json
The existing description for `GITHUB_TOKEN` was copy-pastad. The one for `SENTRY_DSN` needed a little improvement.
> Fix description of some configuration variables

- freight/api/task_details.py
- freight/jobs/execute_task.py
- freight/notifiers/queue.py
- freight/notifiers/utils.py
- tests/notifiers/test_utils.py
This could be improved further by abstracting task updates so they always lock in these situations, but it at least helps the situation where we are mutating the task status vs the execute wrapper reacting from it.
> Improve consistency around task state and notifications

- Procfile
- freight/api/app_details.py
- freight/api/app_index.py
- freight/api/deploy_index.py
- freight/models/app.py
- freight/models/taskconfig.py
- freight/testutils/fixtures.py
- migrations/versions/205fd513c96_added_taskconfig.py
- tests/api/serializer/test_deploy.py
- tests/api/test_app_details.py
- tests/api/test_app_index.py
- tests/api/test_deploy_details.py
- tests/api/test_deploy_index.py
- tests/api/test_deploy_log.py
- tests/notifiers/test_queue.py
- tests/notifiers/test_sentry.py
- tests/notifiers/test_slack.py
- tests/notifiers/test_utils.py
- tests/providers/test_shell.py
- tests/tasks/test_check_queue.py
- tests/tasks/test_delete_object.py
- tests/tasks/test_execute_task.py
- tests/tasks/test_send_pending_notifications.py
This makes TaskConfig a many-to-one with App, allowing multiple
different providers to be configured for an App. This allows different
configurations for deploy/build type tasks.
Right now, this is fully backwards compatible and assumes that the only
type of TaskConfig that will exist is "deploy". This allows the API to
be expanded next to add build configs.
/cc @dcramer
> Split TaskConfig off of App

- tests/api/test_deploy_index.py
The clones in Travis are too shallow to find `master` in it's local refs.
@getsentry/ops 
Related: ![heh](http://www.thepositivemind.com/Pictures/too_shallow.png)
> Changing to a relative branch to fix missing refs.

- bin/run-task
@dcramer: This will prevent us from sitting with a spinning wheel for 600 seconds. Chalked it up to the log line of check pending being the first few bits in the first log chunk, and not getting anything else in there for the timeout.
cc @mattrobenolt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/freight/90)
> Add stale status check reporter.

- freight/api/base.py
- freight/config.py
- freight/exceptions.py
- freight/hooks/__init__.py
- freight/hooks/base.py
- freight/hooks/github.py
- freight/hooks/manager.py
- freight/web/webhooks.py
- tests/web/test_webhooks.py
See https://github.com/getsentry/freight-cli/commit/1f7379e1f4f3d5cf88815b965bea595a69ca6a3d for context on how the webhook url is generated.
It's just a signed url pointing to an app and environment signed with the `API_KEY`, so it's possible to use to generate and sign new webhook urls.
> Support for autodeploy via webhook

- static/components/TaskDetails.jsx
Clicking redeploy now directs to the correct url.
*EDIT*
Renders without reload now.
```javascript
browserHistory.push('/');
browserHistory.push(`/deploys/${data.app.name}/${data.environment}/${data.number}`);
```
This solution is loosely based off workarounds found here: https://github.com/ReactTraining/react-router/issues/1982
> Fixed redeploy button.

- freight/checks/github.py
- tests/checks/test_github.py
When there's a partial success/failure, the contexts set was being
mutated down to being empty. And empty meant the same thing as "all
checks must pass". So this yields a copy of the contexts which are used
strictly for checking against.
> Fix issue where contexts aren't being ignored correctly

- .travis.yml
- requirements.txt
1. Pin node.js to specific version that we know works.
2. Upgrade Psycopg2 because Travis upgraded postgresql and libpq.
> Fix Travis tests: 2018 edition

- docker-entrypoint.sh
#132 added the Google Cloud Platform SDK to this container so that Google Cloud Registry could be used for Docker images.
Unfortunately, most of the ways to authenticate and authorize access to GCP are environment-specific and vary wildly. Instead of relying on environment vars set by `docker run`, this PR checks for a script mounted into the container and runs that instead, allowing everyone to customize their login steps as needed.
> move GCP CLI setup for GCR purposes to separate script

- bin/run-task
- freight/checks/base.py
- freight/checks/cloudbuilder.py
cloudbuilder can't be skipped, even if we want to force a deploy,
otherwise the image won't exist.
So this introduces the ability for checks to be marked required or not
to change what the "force" behavior means.
> Change force deploy behavior for required checks

- package.json
- static/tests/CreateDeploy.test.js
This was never used and caused some npm install errors.
> remove sinon, not used anywhere

- freight/providers/__init__.py
- freight/providers/kubernetes.py
- freight/providers/pipeline.py
- requirements.txt
This change provides a new pipeline provider. A pipeline provider is comprised of steps. The 3 steps being implemented currently are `Shell`, `KubernetesJob`, and `KubernetesDeployment`.
Each step is run sequentially, and if applicable, within a step, in parallel. If any step fails, the rest of the pipeline does not continue.
There is a top level, optional, `kubernetes` configuration block. This controls how to fetch kubernetes credentials, or which context to use for authentication. One of either `context` or `credentials` may be defined, but not both. At the moment, `credentials` only supports sourcing from `gcloud`.
This mirrors behavior of our current `shell` provider, just as a step. No new behavior.
This provides the ability to run a one-off `Job` spec in Kubernetes. The struct here …
> provider: Add pipeline provider

- freight/checks/cloudbuilder.py
Instead, we want to use whatever is active within this context
> cloudbuilder: Don't use application-default credentials

- freight/providers/pipeline.py
The incorrect replica stats were being used in determining the status string (see 
57168b6).
Reference: https://github.com/kubernetes/kubernetes/blob/75d51896125b1cafd9e995212b02ccda9b8a0aed/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/rollout_status.go#L76
Also, the `ProgressDeadlineExceeded` `Progressing` deployment condition is now recognized.
> fix(provider): fix rollout_status_deployment

- static/components/CreateDeploy.jsx
- static/components/Layout.jsx
- static/tests/CreateDeploy.test.js
- static/tests/__snapshots__/CreateDeploy.test.js.snap
- static/tests/__snapshots__/Layout.test.js.snap
This changes the create deploy screen to take a default selected app from
the URL
> feat(ui): Deploy with an app selected

- freight/providers/pipeline.py
It looks like `status_replicas` also is None before it's populated. Unfortunately, [the docs](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/AppsV1beta1DeploymentStatus.md#appsv1beta1deploymentstatus) don't really make this clear.
Oh yeah, this fix is going to have to also be applied to `st-kube`.
Fixes FREIGHT-QV.
> fix(provider): default null value for status_replicas to 0 to avoid TypeError

- freight/checks/cloudbuilder.py
- static/tests/__snapshots__/TaskSummary.test.js.snap
There are (at least) two ways how one can add a repo to Cloud Build: "Github (mirrored)" and via "Cloud Build Github App".
The second way is not supported by Freight at the moment, because `sourceProvenance.resolvedRepoSource.commitSha` does not exist on the build triggered from those repositories:
https://github.com/getsentry/freight/blob/e14c7b0e71e82f82b134401a3cf6c0895b81711c/freight/checks/cloudbuilder.py#L51
This PR adds an (optional) "image_name" attribute that should work for both approaches.
> fix(cloudbuilder): Allow to filter by image name and SHA

- package.json
- static/components/CreateDeploy.jsx
- static/tests/__snapshots__/CreateDeploy.test.js.snap
When you click on "Deploy" while you're at the app list page (or just open /deploy?app=NAME) , the list of environments is not populated properly because the app name is taken from the query parameters later than necessary.
> fix: Prefill environment list properly

- freight/checks/github.py
- freight/checks/github_apps.py
I've brought up this concern in the past that the error message isn't helpful. This "contexts" thing is very API-specific, and [it should really be "statuses"](https://developer.github.com/v3/repos/statuses/#list-statuses-for-a-specific-ref), but I didn't feel like renaming a bunch of variables.
It's resurfaced: https://sentry.slack.com/archives/CTJL7358X/p1589575919289000
So, this improves the error message.
Also, not sure if github_apps is needed.
> ref: better error message for no contexts

- freight/providers/pipeline.py
We'll probably need something more sophisticated in the future, but this will already allow us to deploy to different clusters (regions) in the same build.
> feat(k8s): Allow per-step kubernetes config

- freight/api/deploy_log.py
- static/components/TaskDetails.jsx
Fixes bug with safari reported via @rhcarvalho  https://github.com/getsentry/freight/pull/234#issuecomment-674085791
Use the same dateformat we use in other parts of the api, remove frontend hack.
Not totally sure if that's the right way to access the serializer.
> fix: Change datetime format in deployment logs to match others

- freight/providers/pipeline.py
- requirements.txt
We need this before upgrading K8S masters to 1.16.
More about API deprecations in 1.16: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
> build: Upgrade kubernetes dependency to 11.0.0 and update API clients

- Dockerfile
This time though, I've vendored the static docker executable needed in the new sentry-dev-infra-build-assets bucket. No more downloading a large upstream tarball and extracting it to get one thing. Also upgraded docker to latest.
> build: add docker back

- freight/providers/pipeline.py
- freight/providers/utils.py
- tests/providers/test_shell.py
f/u to https://github.com/getsentry/freight/pull/303. Freight was transparently deleting the config_path I was adding. Now it should raise an ApiError.
> fix(config): add config_path to pipeline provider config keys, and raise ApiError if this happens again

- Dockerfile
- package.json
#297 broke cloudbuild, but went unnoticed since there isn't a github context/status for it
#290 wasn't being applied to the production image
these 2 issues have now been fixed with volta
> build: fix yarn not found and old node with volta

- freight/providers/pipeline.py
https://freight.getsentry.net/deploys/getsentry/staging/2633
This failed because I edited the getsentry config and then found out Freight wrote in the key with `null` during validation.
> fix: use truthy check instead of KeyError

- freight/api/serializer/deploy.py
- freight/vcsremote/__init__.py
- freight/vcsremote/base.py
- freight/vcsremote/dummy.py
- freight/vcsremote/github.py
- freight/vcsremote/manager.py
This provides a way to have some context into the deploys VCS remotes.
This adds GitHub as a VCS remote, since that's primarily what Sentry
uses.
> feat(remotes): Add support for 'VcsRemote's

- freight/config.py
- static/components/DeployChart.jsx
- tests/api/test_stats.py
typically looks like this with adblock on
renamed it looks like this
> fix: Rename 'stats' endpoint to stop adblock from blocking it

- static/components/BarChart.jsx
- static/less/base.less
So we can kill off the jquery tooltip
looks like this
> ref(js): Use custom tooltip for charts

- static/hooks/usePolling.jsx
the `void` in front of the triggerPolling was avoiding the return
> fix(js): Correctly cancel polling on unmount

- static/components/ExpectedChanges.jsx
- static/hooks/useLastDeploay.jsx
- static/hooks/useRemoteChanges.jsx
- static/less/base.less
- static/tests/__snapshots__/CreateDeploy.test.js.snap
- static/views/CreateDeploy.jsx
Adds UI elements that use the remote-changes API
Looks like this
In the future I'd like to have a feature that differentiates what will
be deployed based on the Scope tags. Though we'll need a bit more
configuration for the app to do that.
> feat(ui): Represent remote-changes in create deploy

- static/api.jsx
- static/components/Layout.jsx
- static/hooks/useApi.jsx
- static/hooks/useLastDeploay.jsx
- static/hooks/usePolling.jsx
- static/hooks/useRemoteChanges.jsx
- static/views/AppDetails.jsx
- static/views/CreateDeploy.jsx
- static/views/TaskDetails.jsx
Title says it all. Right now API requests will fire after components
unmount and attempt to update state
> ref(js): Add useApi hook to cancel requests on unmount

- freight/vcs/git.py
- tests/vcs/test_git.py
This actually makes more sense for the use case of listing changes to be
deployed, since we don't want to actually include the most recently
deployed commit.
> ref(git): Make the get_sha_range exclusive

- freight/api/remote_changes.py
- freight/vcsremote/base.py
- freight/vcsremote/github.py
This avoids having to update the local clone of the repo when using the
remote-changes API, which was already pretty flakey due to needing to
lock while using it.
> ref(remotevcs): Add `get_sha_range` using github compare API

- static/components/ExpectedChanges.jsx
We remove the `(#xxx)` string from the end of commit messages, since we'll add our own. Sometimes these are truncated like `(#12...`. This updates the regex to better handle that
> ref(ui): Fix ExpectedChanges message PR title cleanup

- static/components/ExpectedChanges.jsx
sha is not a property, it's oid (object ID)
> fix(ui): Correct bad key in ExpectedChanges

- freight/api/serializer/app.py
- freight/models/app.py
This will provide the UI a way to filter out / mark 'recent changes' that aren't labeled wtih the change_labels.
Powers #369
> feat(labels): Support specifying 'change_labels'

- static/components/ExpectedChanges.jsx
This should have been included in #369
The div is needed so we don't fade out the pseudo elements on the left making up the commit dots and connecting lines.
> fix(ui): Add missing div wrapper for correct commit list styling

- Dockerfile
- docker-entrypoint.sh
- docker/config.json
This is needed for https://github.com/getsentry/getsentry/pull/7994, which removes fabric/remote execution.
It used to be that the Freight container would run on garbage and literally ssh into.... garbage to do stuff as the "build" user. Lol.
Now, since that's trying to run directly inside the Freight container, `/srv/www/getsentry.com` on garbage (build:build uid 9010) needs to be volume mounted.
> feat: adapt to getsentry/getsentry#7994

- static/less/base.less
- static/tests/TaskDetails.test.js
- static/views/TaskDetails.jsx
Last bit and create-react-class and mixins go away.
It's probably easier to review this by just reading the old code and then reading the new component.
It does the following:
1. Polls for task details (to see when the task changes status)
2. Polls for log chunks. Each new log chunk progresses the logOffset and starts polling for that new offset.
3. Keeps scroll at the bottom unless live scroll is tfurned off
4. Highlights the `#Lxx` line number in the hash, and toggles it on and off by clicking timestamps
5. Button to cancel the deploy
6. Button to trigger a redeploy
I've tested all of this, everything looks good 👍
> ref(js): Convert TaskDetails to a FC

- bin/run-task
- static/tests/__snapshots__/TaskSummary.test.js.snap
in theory this will just print the error message instead of the full stacktrace which is pretty confusing
> ref: make the stacktrace less noisy on failures
