getsentry/freight

README.md
I've added the environmental variables that I needed to set in order
to get it working on Heroku.
=> Add a note about setup.

Dockerfile, docker-compose.yml, docker-entrypoint
Got to make docker deploys work! Used this repo to test: https://github.com/marksteve/freight-test-web Should I create an extra page to discuss docker setups? There's still a manual step to create machines though.
=> [WIP] Docker setup improvements

docker-compose.yml
Fix not connect to db and redis
=> Fix config docker-compose

docs/quickstart.rst
A bit raw, I admit, but at least I can copy-paste from this next time I have to setup an application..
=> Add some documentation about notifiers and checks

docs/quickstart.rst, freight/api/task_index.py, freight/db/types/json.py, freight/models/app.py, freight/models/task.py, freight/notifiers/sentry.py, freight/notifiers/slack.py, freight/providers/shell.py, freight/testutils/fixtures.py, migrations/versions/16c1b29dc47c_add_task_params.py, migrations/versions/443ea4d5c205_remove_task_name.py, requirements-test.txt, requirements.txt, setup.py, tests/api/test_controller.py, tests/api/test_task_index.py, tests/providers/test_shell.py
Hi,
It's a work in progress:
* Remove ``Task.name``
* Add ``Task.params`` as mentioned by @dcramer 
* Export ``get_current_sha`` and ``get_previous_sha`` to Task model
* Export requirements to separate files for Docker
Give me your thought about these changes :beer:
=> Add Task.params

bin/worker
=> Fix logic for worker logging.

bin/web, bin/worker, freight/config.py, freight/utils/auth.py
Fixes #68.
@getsentry/ops: Is there anything else we should be doing that is more conducive to development?
=> Implement a --dev flag for bin/{web,worker}.

freight/utils/auth.py
Fixes master and #78.
@getsentry/ops
=> Move fixture import to only be in DEV

freight/notifiers/slack.py
@mitsuhiko thought this would be a good idea.
If it's wroth the extra queries, I'm down.
=> Add the username to operations that can happen in the UI.

freight/notifiers/slack.py
=> Strip domain names from email addresses.

freight/notifiers/slack.py
=> Add mentions to all operations.

Dockerfile, docker-entrypoint.sh
=> Add gosu and tini

freight/checks/github.py, tests/checks/test_github.py
@mattrobenolt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/freight/91)
=> Use Github's full status dict in pending msg.

.dockerignore, docker-entrypoint.sh
@JTCunning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/freight/92)
=> Accept DOCKER_CONFIG environment variable

static/components/TaskDetails.jsx, static/less/base.less
=> Added seconds accuracy to timestamps

.babelrc, package.json, static/components/BarChart.jsx, static/components/DeployChart.jsx, static/components/Duration.jsx, static/components/Overview.jsx, static/components/TaskDetails.jsx, static/components/TaskSummary.jsx, static/components/TimeSince.jsx, static/components/TooltipTrigger.jsx, static/mixins/polling.jsx, webpack.config.js
Upgraded Webpack and added all the extra dependencies need to get it up and running.  Other than that the commit is just a bunch of syntax changes.
=> Upgraded Webpack to 2.2.0 and Webpack-dev-server to ^2.0.0

webpack.config.js
Spelling.  Styles.css != Style.css
=> Webpackfix

static/components/Overview.jsx, static/components/TaskDetails.jsx, static/mixins/polling.jsx, static/pushNotification.js
Freight now has build notifications using the browser notifications api. https://developer.mozilla.org/en-US/docs/Web/API/notification
=> Freight browser notifications.

static/components/Overview.jsx, static/components/TaskDetails.jsx
Now the prompt to either accept or deny notifications will be sent at the first visit of Freight.
=> Added prompt for notifications pre-deploy.

templates/index.html, webpack.config.js
=> Cached Styles

static/less/base.less
=> Highlight has better contrast with red text.

static/components/Overview.jsx, static/components/TaskDetails.jsx, static/pushNotification.js
😬 quick hack for people who use freight on their ipads. i did not run this code
=> safeguard for Notification api being present

static/components/TaskDetails.jsx
i still don't have a working dev environment but i stepped through the live version and feel decently confident abt this fix
=> don't snap to bottom on finished builds

Dockerfile, docker-entrypoint.sh
@JTCunning - I worked with @evralston and this is ready to merge so that we can further test functionality
=> Add support for pushing to Google Cloud Registry

freight/checks/cloudbuilder.py, tests/checks/test_cloudbuilder.py
Applying feedback from @mattrobenolt
=> WIP Cloudbuilder feedback from matt

freight/checks/__init__.py, freight/checks/github_apps.py, tests/checks/test_github_apps.py
Can be used e.g. for travis-ci.com checks. 
Example payload: https://gist.github.com/tonyo/3ed08e321e16a33a754b8c6fd3e68f2d
=> feat: Add 'github-apps' check type

package-lock.json, package.json
=> ref(js): Remove `anchor-js`, `arr-diff`, and `bundle-loader`

package-lock.json, package.json, static/components/TaskDetails.jsx
Uses [linky-urls](https://github.com/sindresorhus/linkify-urls) to search for URLs in strings and changes them to a link.
Depends on #183
=> feat(ui): Linkify URLs in log

.babelrc, freight/api/base.py, freight/api/config.py, package-lock.json, package.json, static/components/Layout.jsx, static/tests/__snapshots__/Layout.test.js.snap, webpack.config.js
Fixes webpack-dev proxies to redirect some additional server side routes (auth, webhooks)
=> fix(ui): Fix non-authed state

Dockerfile
...again, because some bug fixes.
=> feat: Update sentry-cli to 1.47.2

freight/api/stats.py, static/components/AppDetails.jsx, static/components/AppSettings.jsx, static/components/DeployChart.jsx, static/components/Layout.jsx, static/tests/Layout.test.js, static/tests/__snapshots__/Layout.test.js.snap
* Show application name when you are in app details
* Show app scoped deploy chart history
=> feat(ui): Allow linking to application scope

freight/providers/pipeline.py
Remove environment_config from PipelineContext and configure number of updated
instance in statefulset from the step configuration.
Environment configuration on the `App` model contains only the `defaultRef` configuration everything else is ignored in serializer. (https://github.com/getsentry/freight/blob/master/freight/api/serializer/app.py#L10-L12)
Therefore it's not possible to use env to configure `statefulset_instances`.
This PR implements suggestion by @mattrobenolt with configuration in step per env name (https://github.com/getsentry/freight/pull/241#pullrequestreview-478015006).
```yaml
instances:
env_name: 1  # number of instances to update
```
=> Configure the statefulset_instances from step

freight/checks/github_apps.py, tests/checks/test_github_apps.py
GithubApps check is using the check runs Github API (https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#list-check-runs-for-a-git-reference)
For some PRs the API returns a total count of more than the per page 100 limit. In such a case the call returns a status and conclusion data for only 30 check runs.
This PR introduces pagination so Freight retrieves all check runs data.
=> Paginate the check runs api to retrieve all check runs for commit

Dockerfile
Freight's crashlooping. Best guess is likely Python 3.8.1 -> 3.8.12 and the very old gcloud sdk broke. Anyways, it should be upgraded as well since it's supposed to run on 2.7.
```
May  3 02:16:57 garbage a90e8aeec5bd[1387]: + exec alembic upgrade head
May  3 02:16:58 garbage kernel: [49341090.413488] IPv4: martian source 172.19.0.2 from 172.19.0.3, on dev eth0
May  3 02:16:58 garbage kernel: [49341090.413493] ll header: 00000000: ff ff ff ff ff ff 02 42 ac 13 00 03 08 06        .......B......
May  3 02:16:59 garbage kernel: [49341090.899260] IPv4: martian source 172.19.0.2 from 172.19.0.5, on dev eth0
May  3 02:16:59 garbage kernel: [49341090.899265] ll header: 00000000: ff ff ff ff ff ff 02 42 ac 13 00 05 08 06        .......B......
May  3 02:16:59 garbage 30ff5a95d674[1387]: …
```
=> chore: upgrade gcloud sdk

README.rst, app.json, docs/quickstart.rst, freight/config.py, requirements.txt
We don't intend to support Heroku anymore.
=> ref: remove heroku

README.md, setup.py
=> chore: README.{rst -> md}

Procfile, Procfile.dev
Confirmed with cramer this is fine
=> chore: Remove Procfile, we don't use heroku for this

bin/web, docs/quickstart.rst, webpack.config.js
See: https://old.reddit.com/r/webdev/comments/qg8yt9/apple_took_over_port_5000_in_the_latest_macos/
=> ref(dev): Use port 5001 in development

static/components/Duration.jsx, static/components/ListLink.jsx
=> ref(js): Always use ES imports

static/less/base.less
=> fix(ui): Align commits

package.json, static/api.jsx, static/components/AppDetails.jsx, static/components/CreateDeploy.jsx, static/components/DeployChart.jsx, static/components/FaviconStatus.jsx, static/components/Layout.jsx, static/components/Overview.jsx, static/components/TaskDetails.jsx, static/mixins/polling.jsx, static/tests/DeployChart.test.js, static/tests/Layout.test.js, static/tests/TaskDetails.test.js, static/tests/__snapshots__/DeployChart.test.js.snap, static/tests/__snapshots__/Layout.test.js.snap, static/tests/__snapshots__/TaskDetails.test.js.snap, static/tests/setup.js, yarn.lock
A bit more modern. Makes things a bit more clear too
=> ref(js): Use async API request interface

tsconfig.json
=> feat(ts): Add tsconfig

static/views/CreateDeploy.jsx
Going to be making a number of changes to this component
=> ref(js): Convert CreateDeploy to a FC

static/components/ExpectedChanges.jsx, static/less/base.less, static/tests/CreateDeploy.test.js, static/tests/__snapshots__/CreateDeploy.test.js.snap, static/views/CreateDeploy.jsx
=> feat(deploy): Show previous deploy on deploy screen

freight/api/remote_changes.py, freight/config.py, freight/vcsremote/base.py, freight/vcsremote/github.py
This API returns a list of changes from the remote, given a start and end ref.
Currently this is implemented for the GitHub VCS remote, and will result in a list of pull commits with associatedPullRequests and externalCommit keys, which will be useful for the UI to generate a concise list of changes.
---
Implementation details:
When the /remote-changes/?startRef=master&endRef=master^^ API is called we do the following...
1. Clone / update the repo into the workspace. For most freight projects this will be an update operation.
2. Use the VCS backend to get the sha list between the start and end ref. When used in the UI this will likely be the changes between master and whatever was last deployed.o
3. pass the sha list into the github `vcsremote` and use the graphql API to pull down …
=> feat(remotevcs): Add /remote-changes/ API

static/less/base.less, static/views/TaskDetails.jsx
Instead of repeating the same element
Looks marginally different
Old style
I'll revisit later, but the code-deduplication here is good
=> ref(ui): Use TaskSummary in TaskDetails

static/views/TaskDetails.jsx
This was just calling the function, it needs to pass the function
=> fix(ui): Fix prop updates handling in TaskDetails

package.json, yarn.lock
=> chore(js): Bump classnames

static/less/base.less
=> fix(ui): Alignment of app name for deploy

static/components/ExpectedChanges.jsx, static/less/base.less, static/tests/__snapshots__/CreateDeploy.test.js.snap, static/views/CreateDeploy.jsx
=> feat(ui): Visually highlight changes w/ changeLabels

static/hooks/usePolling.jsx
Fixes a few things
1. timeout and backoffTimeout are now configurable.
2. Because of the nature of JavaScript closures, our `setTimeout` was using a stale `triggerPolling` callbacks. We fix this by keeping the triggerPolling (renamed to just triggerRef) in a ref and introduce a new `enqueNextTrigger` callback.
3. A small behavior change makes it so the first request will ALWAYS happen, even if pollingActive is disabled.
=> fix(js): Improve robustness of usePolling

static/mixins/polling.jsx
There's only one usage of this left.
=> fix(ui): Unbreak PollingMixin

freight/providers/pipeline.py
=> fix: Lint error

static/views/LockDeploy.jsx
This was causing issues in firefox
=> ref(js): Use type="button" for non-submit buttons
